name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer    
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild build CODE_SIGN_IDENTITY="-"
    - name: Test
      run: xcodebuild test -scheme disabled-wifi CODE_SIGN_IDENTITY="-"
