name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild build
    - name: Test
      run: xcodebuild test -scheme disiabled-wifi
